name: bumper

on:
  push:
    branches:
      - '**'

jobs:
  bump:
    name: Bump yaml
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get backend tag
        id: get-backend-tag
        run: echo "::set-output name=tag::$(cat version-file)"

      - name: Checkout applications-infra repository
        uses: actions/checkout@v2
        with:
          repository: gagarinfan/yaml-action-test-main
          ref: main
          token: ${{ secrets.PAT }}
          path: yaml-action-test-main

      - name: Bump version in dev umbrella chart
        uses: microsoft/variable-substitution@v1 
        with:
          files: 'yaml-action-test-main/some-file.yaml'
        env:
          version: ${{ steps.get-backend-tag.outputs.tag }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: yaml-action-test-main
          token: ${{ secrets.PAT }}
          branch: feature/backend-tag-${{ steps.get-backend-tag.outputs.tag }}
          title: Update backend image tag to ${{ steps.get-backend-tag.outputs.tag }}
          commit-message: Update backend image tag to ${{ steps.get-backend-tag.outputs.tag }}
          author: ${{ github.actor }}