name: updater

on:
  push:
    branches:
      - '**'

jobs:
  test-and-publish:
    name: Update yaml
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check conditions to deploy on dev
        id: deploy-to-dev
        if: |
          github.ref == 'refs/heads/main' &&
          !contains(github.event.head_commit.message, 'Bump version')
        run: |
          if ! [ $(git diff --name-only HEAD HEAD~1 | grep -Ev "some-yaml.yaml" | wc -l) -eq 0 ];then
            echo "::set-output name=match::false"
          else
            echo "::set-output name=match::true"
          fi

      - name: Validate yaml
        if: steps.deploy-to-dev.outputs.match
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: 'some-yaml.yaml'

      - name: Get backend tag
        if: steps.deploy-to-dev.outputs.match
        id: get-backend-tag
        run: echo "::set-output name=tag::$(cat version-file)"

      - name: Replace in yaml
        if: steps.deploy-to-dev.outputs.match
        uses: microsoft/variable-substitution@v1 
        with:
          files: 'some-yaml.yaml'
        env:
          server.image.tag: ${{ steps.get-backend-tag.outputs.tag }}

      - name: Push to main
        uses: colmose/push-bot@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch_name: 'main'
          bot_name: 'CI-bot'
 
