name: updater

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  test-and-publish:
    name: Update yaml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check conditions to deploy on dev
        id: deploy-to-dev
        if: startsWith(github.ref, 'refs/tags/v') != true && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'Bump version')
        run: echo "::set-output name=match::true"

      - name: Get backend tag
        if: steps.deploy-to-dev.outputs.match == 'true'
        id: get-backend-tag
        run: echo "::set-output name=tag::$(cat version-file)"

      - name: Replace in yaml
        if: steps.deploy-to-dev.outputs.match == 'true'
        uses: microsoft/variable-substitution@v1 
        with:
          files: 'some-yaml.yaml'
        env:
          server.image.tag: ${{ steps.get-backend-tag.outputs.tag }}

      - name: Commit
        if: steps.deploy-to-dev.outputs.match == 'true'
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated report"
          git push