name: updater

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  test-and-publish:
    name: Update yaml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate yaml
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: 'some-yaml.yaml'

      - name: Check conditions to deploy on dev
        id: deploy-to-dev
        if: |
          github.ref == 'refs/heads/main' &&
          !contains(github.event.head_commit.message, 'Bump version')
        run: |
          if [ $(git diff --name-only main HEAD HEAD~1 | wc -l) -eq 1 ] && [ $(git diff --name-only main HEAD HEAD~1 | grep some-yaml) ];then
            echo "::set-output name=match::true"
          fi

      - name: Get backend tag
        if: steps.deploy-to-dev.outputs.match
        id: get-backend-tag
        run: echo "::set-output name=tag::$(cat version-file)"

      - name: Replace in yaml
        if: steps.deploy-to-dev.outputs.match
        uses: microsoft/variable-substitution@v1 
        with:
          files: 'some-yaml.yaml'
        env:
          server.image.tag: ${{ steps.get-backend-tag.outputs.tag }}

      - name: Commit
        if: steps.deploy-to-dev.outputs.match
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated report"
          git push